### ISSUE TITLE
精彩的工作

### ISSUE THREAD

**Issue by MKSAQW** [LiheYoung/UniMatch-V2#1]
很荣幸看到UniMatch的第二个版本，请问有论文的链接嘛，我很想拜读一下原文

**Comment by LiheYoung** [comment]
你好，感谢关注，我们明早会挂在arxiv上。

**Comment by MKSAQW** [comment]
感谢感谢

**Comment by MKSAQW** [comment]
请问本文中采用的A100GPU是40G的还是80G的呀

**Comment by LiheYoung** [comment]
你好，我们40G和80G都有使用，除了Cityscapes的实验必须要在80G上跑，其他实验都可以在40G A100上完成。

**Comment by MKSAQW** [comment]
好的，谢谢您

**Comment by likyoo** [comment]
👍 👍 👍
