### ISSUE TITLE
未来的研究方向

### ISSUE THREAD

**Issue by emerald876** [LiheYoung/UniMatch-V2#3]
作者大大，看了实验组对半监督语义分割的几篇论文后，觉得很厉害，想请教一下，未来还有哪些部分值得继续研究下去呢

**Comment by LiheYoung** [comment]
我个人觉得比较值得探索的是在真实场景下，当存在较多的有标签数据和海量规模（>10M）的无标签数据下如何发挥半监督的作用。现有的这些benchmark都是在比较少的数据下去验证的，很多结论可能都不具有可扩展性，很toy。我们在V2里面朝着大规模无监督做了一些初步的探索，我们用了几万张有标签图像和几十万的无标签图像去验证半监督的作用，但这个和真实情况下的数据量依然有很大差距。

在大规模数据下，对于原图的筛选（例如要平衡各个concept的图像的数量）以及伪标签的筛选，应该是特别重要的。

**Comment by emerald876** [comment]
感谢解答，期待你们更优秀的方法
