### ISSUE TITLE
The perfect job.

### ISSUE THREAD

**Issue by LLlovecat** [LiheYoung/UniMatch-V2#4]
I have trained a model, but the subsequent visualization please ask the author how it is presented, thank you very much for your contribution!
![捕获1](https://github.com/user-attachments/assets/8f8e5239-5e91-4143-b154-e6e746c6777f)

Can you provide the code for the relevant visualization? Want to reproduce your great work！
![捕获22](https://github.com/user-attachments/assets/6ba6d8ba-cda9-4a67-968a-d4e09d2ea5b7)

**Comment by LiheYoung** [comment]
可以参考这里面的code: https://github.com/ZhenZHAO/AugSeg/issues/11

**Comment by LLlovecat** [comment]
Thank you very much for your reply. Can you provide me with your visualization file? I saw the link you sent me, but I don't have the .yaml file for the code, I hope you can help me, and finally, thank you very much for your help, and good luck with your research!

**Comment by AKAsanmu** [comment]
> 非常感谢您的回复。您能提供您的可视化文件吗？我看到了您发送给我的链接，但我没有代码的 .yaml 文件，希望您能帮助我，最后，非常感谢您的帮助，祝您的研究好运！

Hello, I have encountered the same problem as you. Have you solved it? If so, could you please provide your code? Thank you very much.
