### ISSUE TITLE
Memory requirements for DINO small

### ISSUE THREAD

**Issue by EduardoLawson1** [LiheYoung/UniMatch-V2#5]
How much memory it is necessary to train DINO small? Can be the least, like split 92 in the pascal voc dataset

**Comment by LiheYoung** [comment]
It requires 10G/GPU x 4 GPUs for DINOv2 small, and 20G/GPU x 4GPUs for DINOv2 base.

**Comment by Kthulhut** [comment]
If you use "lock_backbone: True" you need less memory. Results are slightly different but in my case they still look good.
I actually running on only one GPU with only 4 GB memory with:
pascal voc, split='366', lock_backbone: True 
Start Training with "train.sh 1 29500"
All other settings are default as in the repo.

After 7 Days training time i got:
INFO] ===========> Epoch: 30, Previous best: MeanIoU: 84.13 @epoch-28, EMA: 84.47 @epoch-29
