### ISSUE TITLE
关于在blended PASCAL VOC2012数据集上的实验

### ISSUE THREAD

**Issue by PixelSegTech** [LiheYoung/UniMatch-V2#6]
您好，非常感谢您卓越的工作，我深受这篇论文的启发，请问UniMatchV2在blended PASCAL VOC2012数据集上有过探究嘛

**Comment by LiheYoung** [comment]
你好，我们没有尝试这个划分。在blended split上，以前的工作有很多不公平的对比，因此我们忽略了这个划分。我们认为直接从high-quality set里去labeled images更合理，也已经足够了。
